### ISSUE TITLE
Delete monitoring objects when devices are deleted

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-monitoring#1]
When a device is deleted, its related metric and check (eg: ping) are not deleted.
Ideally we should delete the related objects automatically ~~and make it easy to recover these via django-reversion~~.

**Comment by nepython** [comment]
I am working on this :smiley:

**Comment by nepython** [comment]
@nemesisdesign, will it be fine if I create a custom delete action because I thought it would be best to display the related metrics and check which shall get deleted, so this will help to modify the **delete selected devices** page to display the same.

**Comment by nemesisdesign** [comment]
@nepython it should be done with a post_delete signal, hooked in the ready method of this class: https://github.com/openwisp/openwisp-monitoring/blob/master/openwisp_monitoring/check/apps.py

Like here: https://github.com/openwisp/openwisp-controller/blob/master/openwisp_controller/connection/apps.py#L15-L29
