### ISSUE TITLE
[metrics] Measurement stored in InfluxDB aren't deleted when related metrics are deleted.

### ISSUE THREAD

**Issue by nepython** [openwisp/openwisp-monitoring#101]
When a metric is deleted the related measurement in the influxdb is not deleted, ideally that should be the case. Since, it might lead to lesser data stored in the timeseries db
**Possible Solution**: Using a pre-delete signal and sending relevant query to InfluxDB

**Up for Discussion**
* Should we delete it or not?
* If not we shall document this behavior

**Comment by PabloCastellano** [comment]
Documentation: https://docs.influxdata.com/influxdb/v1.8/guides/downsample_and_retain/

**Comment by PabloCastellano** [comment]
I tend to think that we should not delete old data. Maybe we can add a message making it clear that deleting a Metric object will not delete its stored data in the database.

IMHO the quantity of data we already store is insignificant and we shouldn't worry at this point about making such optimizations.

But event though I have said that, this could be an improvement that we could do in the future. The user could choose to delete the stored data too when deleting a Metric object

**Comment by nemesifier** [comment]
Should have been solved by https://github.com/openwisp/openwisp-monitoring/pull/429.
