### ISSUE TITLE
[settings] Review OPENWISP_MONITORING_CHARTS and ADDITIONAL_CHARTS

### ISSUE THREAD

**Issue by PabloCastellano** [openwisp/openwisp-monitoring#124]
The following settings may become useless after https://github.com/openwisp/openwisp-monitoring/pull/117 has been merged:
* OPENWISP_MONITORING_CHARTS
* ADDITIONAL_CHARTS

Check the following comments for context:
* https://github.com/openwisp/openwisp-monitoring/pull/117#issuecomment-639828392
* https://github.com/openwisp/openwisp-monitoring/pull/117#pullrequestreview-426132616

**Comment by nemesisdesign** [comment]
We concluded that register/unregister should be used to extend openwisp-monitoring when one needs to add custom funcionality., the settings instead should be used to change the default settings.
