### ISSUE TITLE
[alerts] Alert being sent on first metric collection

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-monitoring#125]
I've been testing the new metrics added by @nepython and I noticed something that needs to be improved.

Expected behavior:

- metrics are collected and are within the allowed values (eg: CPU is lower than 90%, etc)
- no alert is sent unless

Actual behavior

- RECOVERY alerts are sent

The system some how consider the first metric collection as a recovery, we must avoid this.

@nepython can you please help me to find the cause of this bug, write a test for it and propose a fix?

**Comment by nepython** [comment]
I was aware of the actual behavior and thought that it is what was expected.
