### ISSUE TITLE
[monitoring] Move check into monitoring app

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-monitoring#13]
We should move check in `openwisp_monitoring.monitoring` since it makes sense that it's part of the main monitoring solution. It's still good to keep the code separated, but it should be configured in a way that it shows up under the monitoring app and not in its own app.

We should make sure any DB migration generated by this change performs the migration in a backward compatible way.

**Comment by Purhan** [comment]
@nemesisdesign I'm not sure if my implement is headed in the right direction, please check the draft PR above

**Comment by nemesisdesign** [comment]
I think there's no real necessity of doing this. I will close for now, if the need arises we'll reopen.
