### ISSUE TITLE
[metrics] rx_bytes vs tx_bytes

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-monitoring#133]
Right now two `Metric` objects are being created for each traffic measurements.
I wonder if we can avoid this and have just one metric created. It should be possible.

**Comment by nepython** [comment]
It should be possible and sounds more reasonable to do so considering that both metrics communicate with a single measurement in `InfluxDB`.

**Comment by nemesisdesign** [comment]
@nepython can this be closed?
Is the README updated? I still see two different metrics in the README, if the README is outdated please update it.

**Comment by nemesisdesign** [comment]
@nepython can this be closed?

**Comment by nepython** [comment]
> @nepython can this be closed?

Yes 👍
