### ISSUE TITLE
React to metric collection and checksum signals

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-monitoring#14]
## 1. Listen to the health status change signal

Whenever the status moves into critical, a cache key with the device UUID is created, eg:

`device-<pk>-react-to-updates` which should be set to `1`

If the health status moves to any other status, the key is set to `0' 

## 2. Emit a new signal when device metrics are received

Now add the code to emit a signal when device metrics are collected (`DeviceMetricView`, before a succesful response is returned).

## 3. React to the signals

Add a receiver for this new signal and for the device configuration checksum signal described here: https://github.com/openwisp/django-netjsonconfig/issues/174

The receiver connected to those signals should check the cache key described above and if  the value is 1, we shall queue the celery task to be run in the background, if it's 0 we skip.

The celery task shall find out if there's any check related to the device, if there is any it shall trigger the checks to be run in the background.

If there's no related check, move the status to OK.

The goal of this issue is to make the monitoring system faster in detecting recoveries because checks are run periodically (eg: 5 minutes). With this new solution we'll be able to find out recoveries as soon as they happen.

## 4. Behaviour configurable

Add a setting which controls this behaviour, defaulting to `True`.
If set to `False` these reactions will be disabled.

The name of the setting can be: `OPENWISP_MONITORING_DEVICE_REACTIONS`.

Do not forget to add a mention to this setting in the README.

**Comment by nepython** [comment]
Working on it :smiley:
