### ISSUE TITLE
[migrations] Squash migrations

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-monitoring#169]
Once we're ready for the first release and once all the existing deployed systems using the development version have been updated, we should squash the migrations to make our life easier.

Once the squashing is done, ensure the migrations can be ran backward without errors, see https://github.com/openwisp/openwisp-monitoring/pull/216#pullrequestreview-476335066 for more info.

**Comment by nepython** [comment]
@nemesisdesign, do you have any plans regarding upto what extent we should squash the migrations. Right now, I have squashed all 23 migrations in monitoring app and am testing it locally to see if there are any issues. Imo we can keep the migrations in device_monitoring app unsquashed and squash the [first two in check app](https://github.com/openwisp/openwisp-monitoring/tree/master/openwisp_monitoring/check/migrations) to ensure the ones having RunPython stay separate :)

**Comment by atb00ker** [comment]
@nepython 
Ideally, we want to squash all the unreleased ones into one migrations file only.
However, this not being an ideal world, there are 2 cases where I can definitely think we need multiple migration files:
1. People are already using the module and squashing would mess up their existing systems.
2. Migration A is dependent  on Migration B.

Other than that there is no hard and fast rule of squashing migration or not.
If the migration file is getting too big, I suppose moving python functions separately would make sense.

Why don't you squash in the manner you think is the best and then let's look at the code to judge if it will be better to make any changes to it.

What do you think?

**Comment by nemesisdesign** [comment]
Thanks for taking the time to ask @nepython.

I think we have to keep in mind these points:

- there are different instances using this unreleased version so we just have to make sure they'll be able to upgrade their systems
- some data migrations are useful for adding openwisp-monitoring to existing systems, eg:  https://github.com/openwisp/openwisp-monitoring/blob/master/openwisp_monitoring/check/migrations/0005_create_config_applied.py, we can keep these as they are
- other data migrations are used just to convert the data from old DB schema to the new one, so we should be able to skip those
- we can keep unsquashed migration files in the repository and schedule them for removal in the 0.2 version

**Comment by nepython** [comment]
Thanks @atb00ker @nemesisdesign, I went ahead to create #253 after taking in your feedback :)
