### ISSUE TITLE
Prepare 0.1 release

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-monitoring#203]
Prerequisites:

- [x] #207 
- [x] #206
- [x] #205
- [x] #204 
- [x] #201 
- [x] #202 
- [x] #199 
- [x] #182
- [x] #169 
- [x] #167
- [x] first release of openwisp-notifications

After this list is completed, we can go ahead and issue the first release! :clap:

**Comment by PabloCastellano** [comment]
@nemesisdesign Nice to see that the release date is so close now! I think you already know it, but GitHub milestones are useful to track the pending issues for a release

**Comment by nemesisdesign** [comment]
@PabloCastellano thanks for the suggestion, I created the milestone in this repo: https://github.com/openwisp/openwisp-monitoring/milestone/1
For the issues in the other repos we'll rely on the link here I guess.

**Comment by nemesisdesign** [comment]
Only 4 issues left for 0.1 release!

**Comment by nepython** [comment]
> Only 4 issues left for 0.1 release!

This is so close for an initial release now, I will try to work upon lua-monitoring issue right now :smile:

**Comment by nemesisdesign** [comment]
Finally :+1:
