### ISSUE TITLE
[feature] Auto install the monitoring scripts

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-monitoring#204]
We need to automatically install the monitoring scripts, at least until we [convert lua-monitoring into an openwrt package](https://github.com/openwisp/lua-monitoring/issues/6), but I'm not sure when we'll be able to do that, I'd love to do it, but I just don't have the time now.

Here's how I would do it:

- define some internal variables which describe each of the aspects of the monitoring template: https://gist.github.com/nemesisdesign/cb005dc80a75536cf8537105c3038a71
- we should name the variable something like `TEMPLATE_OPENWISP_MONITORING_01`, `TEMPLATE_NETJSON_MONITORING_01`, `TEMPLATE_CRONTAB_MONITORING_01` (01 gives us the possibility to introduce new versions if needed and update the template)
- we should then create a data migration which looks for a template with some of the aspects which shouldn't change, file names for example, if this template already exists, the data migration should do nothing, if it doesn't exist, the data migration should create it (`organization=None` to make it available to all organizations) and flag it as default

We should then document this aspect, we should state that:

- the monitoring script is required to make some metrics and checks work (point to the metrics and checks with links)
- explain very briefly how the script works, just to give an idea to our users
- list the OpenWRT dependencies needed for the monitoring scripts to work (check `/usr/sbin/update-openwisp-packages` in the linked gist to find out)

**Comment by nepython** [comment]
@nemesisdesign I am having few doubts on how it should be implemented. I have opened a draft PR #258 (needs much work on docs, testcases, etc) which you can give a quick glance and let me know if I am on the right track, thanks.
