### ISSUE TITLE
[monitoring] Wait and retry if influxdb is not ready

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-monitoring#21]
If influxdb is starting up, this may fail: https://github.com/openwisp/openwisp-monitoring/blob/master/openwisp_monitoring/monitoring/apps.py#L15

We should catch that failure, log a warning, wait something like 3 seconds and try again and repeat this procedure 5 times before giving up.

Once we implement this, we can remove this: https://github.com/openwisp/openwisp-monitoring/blob/master/.travis.yml#L36

**Comment by nepython** [comment]
I am working on it :smiley:

**Comment by nepython** [comment]
@nemesisdesign, what needs to be done incase max retries exceed?

**Comment by nemesisdesign** [comment]
@nepython let it fail by raising the exception again, eg:

```python
try:
  ...
except <ExceptionClassUsed> as e:
  raise e
```
