### ISSUE TITLE
[cleanup] Move connection notification logic to openwisp_controller.connection

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-monitoring#226]
To be done after https://github.com/openwisp/openwisp-controller/issues/269.

After https://github.com/openwisp/openwisp-controller/pull/265 is merged we should move the [connection notification logic](https://github.com/openwisp/openwisp-monitoring/blob/master/openwisp_monitoring/device/apps.py#L104-L182) to `openwisp_controller.connection`, because it's not really related to openwisp-monitoring but to openwisp-controller instead.

We had implemented it here because the notifications feature was part of ow-monitoring, but now it's a base module on which openwisp-controller will depend, so we can finally move this code where it belongs. 

Related to https://github.com/openwisp/openwisp-controller/issues/269.

**Comment by NoumbissiValere** [comment]
I am handling this :smile:
