### ISSUE TITLE
is 'openwisp_monitoring.notifications' needed in INSTALLED_APPS?

### ISSUE THREAD

**Issue by pniaps** [openwisp/openwisp-monitoring#233]
I see it's used in https://github.com/openwisp/openwisp-monitoring/blob/bcc3ccd7f3a2ab892dac2e8cc1d3280b78026a93/tests/openwisp2/settings.py#L53 but is not documented in https://github.com/openwisp/openwisp-monitoring/blob/master/README.rst#setup-integrate-in-an-existing-django-project

What happends if not used? I see it has migrations, but don't know if they are executed/needed or not.

**Comment by nepython** [comment]
@pniaps, notifications module was earlier included in the monitoring module. It has now been decoupled and is going to be extensively used along with other OpenWISP modules besides the monitoring module.
The migration scripts that are there in openwisp_monitoring.notifications were kept to have successful data migration from the app openwisp_monitoring.notifications to openwisp_notifications in some production instances which were already using openwisp_monitoring.notifications.

So yes, openwisp_monitoring.notifications is longer needed in INSTALLED_APPS.

I think we can remove it when monitoring module nears first release provided all production instances have successfully made a data migration. Wdyt @nemesisdesign @pandafy ?

**Comment by pniaps** [comment]
Thanks for the explanation.

This documentation is for a new project, so it's correct. Maybe not in the test project (should be removed?).

**Comment by nemesisdesign** [comment]
I think we should be able to remove it now, what do you think @pandafy?

**Comment by pandafy** [comment]
Yeah, it should be completely fine to remove `openwisp_monitoring.notifications`

> I think we can remove it when monitoring module nears first release provided all production instances have successfully made a data migration.

I agree with @nepython on this, maybe we can remove it from installation documentations but keep the code and add a pointer in FAQs/Troubleshooting guide.

**Comment by nemesisdesign** [comment]
I confirm It's safe to remove it!

**Comment by nepython** [comment]
Why haven't we removed the migration files of the notifications app before closing this issue?
> I confirm It's safe to remove it!

If all production instances have been successfully upgraded to use `openwisp_notifications` then migration files can be deleted before the initial release imo.

**Comment by nemesisdesign** [comment]
> Why haven't we removed the migration files of the notifications app before closing this issue?
> 
> > I confirm It's safe to remove it!
> 
> If all production instances have been successfully upgraded to use `openwisp_notifications` then migration files can be deleted before the initial release imo.

I didn't notice the migration files were not removed, I'm reopening!
