### ISSUE TITLE
[docs] ReStructuredText syntax error catched by openwisp-utils development version

### ISSUE THREAD

**Issue by devkapilbansal** [openwisp/openwisp-monitoring#239]
Running quality assurance tests, (installed from the development version of openwisp-utils), raises this error

```
There are some Errors in your RST file syntax 

- <string>:1181: (ERROR/3) Unknown target name: "django documentation https://docs.djangoproject.com/en/dev/howto/custom-management-commands/>".
```

Install the dev version of openwisp-utils with `pip install -U http://github.com/openwisp/openwisp-utils/tarball/master`.

**Comment by devkapilbansal** [comment]
@nemesisdesign @atb00ker is this issue relevant? I was testing RST check for which I have to use the latest version of openwisp-utils.

**Comment by nemesisdesign** [comment]
@devkapilbansal yes, looks like there's a RST syntax issue in that line. PS: next time use text instead of image, is more practical in these cases. Use images when showing UI issues.

**Comment by devkapilbansal** [comment]
> @devkapilbansal yes, looks like there's a RST syntax issue in that line. PS: next time use text instead of image, is more practical in these cases. Use images when showing UI issues.

Updated. :+1:  Also, with RST syntax issues, there is one more right after that

**Comment by vipermark7** [comment]
I'll take a crack at this! :)
