### ISSUE TITLE
[feature] Charts: allow specifying range of dates

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-monitoring#26]
Allow specify by custom date range: the user will be able to select a range of dates and reload the graphs for the dates specified.

First the backend and API must be changed, then the HTML template and JS code.
The grouping of the timeseries must adjust to the length of the range automatically.

The grouping is defined here: https://github.com/openwisp/openwisp-monitoring/blob/master/openwisp_monitoring/monitoring/models.py#L310

For example, right now, 1 day intervals group results by 10 minutes. While 3 day intervals group results by 20 minutes.

The system could determine the optimum grouping automatically, ranging from 5 minutes (specific days) up to 24 hours (ranges up to 1 year).

Possible steps:

- [ ]  add possibility to filter data by date range in API / model
- [ ] change group_by so that the amount of points shown is constant
- [ ] offer different resolutions (standard, high, maximum), which will reflect on group_by so that the number of points shown (resolution) can be increased if needed

Notes:
- [ ] ensure group by is never lower than default interval
- [ ] make default interval configurable (default to 5 minutes) and change the celery beat setting to use it + update docs

The minimum range is 1 day, the maximum range is 1 year.

**Comment by yashikajotwani12** [comment]
I am using https://www.daterangepicker.com/ for enabling the range of dates.

**Note**: After we add this section of selecting dates, this current section of  `1 day`, `3 days`, and so on, can be removed, and instead we would be able to access this through `today`, `yesterday`, and so on.

![Screenshot (77)](https://user-images.githubusercontent.com/77020164/176359700-cdcd76a3-5b38-4301-a79f-7634cfe2179d.png)

![Screenshot (80)](https://user-images.githubusercontent.com/77020164/176361881-01736eff-c4a2-4ea3-ba7a-44b42c57008c.png)


![Screenshot (79)](https://user-images.githubusercontent.com/77020164/176361063-9f213a14-3cc2-4ce2-9469-9ed17900a2a5.png)

![chrome-capture-2022-5-29](https://user-images.githubusercontent.com/77020164/176361396-9fad4405-f8ed-45f4-960e-a47fcc63f811.gif)

**Comment by yashikajotwani12** [comment]
**Update**: 

![Screenshot (81)](https://user-images.githubusercontent.com/77020164/176735896-797f3447-c271-46f2-a41e-9b7d2d1e19db.png)

https://user-images.githubusercontent.com/77020164/176736217-e6ed088f-d1b9-47ea-8a3b-2393f78c0bbc.mp4

**Comment by nemesisdesign** [comment]
@yashikajotwani12 good progress, can you please invert the position of export data and the date widget?

Can you also make sure that these buttons look good on narrow screens too? What happens on mobile phones or tables?

**Comment by yashikajotwani12** [comment]
> @yashikajotwani12 good progress, can you please invert the position of export data and the date widget?
> 
> Can you also make sure that these buttons look good on narrow screens too? What happens on mobile phones or tables?

Yeah! I will invert the buttons, and also check for different dimensions :+1:
