### ISSUE TITLE
[ci] Migrate CI build to Github actions

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-monitoring#261]
This repository consumes a lot of build time from Travis.
Let's move the CI build to Github actions as we did for these other modules:

- https://github.com/openwisp/openwisp-radius/pull/200
- https://github.com/openwisp/openwisp-controller/pull/329

**Comment by devkapilbansal** [comment]
I will look into this

**Comment by devkapilbansal** [comment]
Accidentally closed the issue by merging PR on my fork for testing. Reopened now
