### ISSUE TITLE
[feature] Zooming graphs: reload data in order to provide a detailed view

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-monitoring#27]
Depends on https://github.com/openwisp/openwisp-monitoring/issues/26.

Let's say we're viewing a graph for 1 year of data and we zoom in to 2 specific days in which an incident happened.

Right now we wouldn't see much, because the zoom will simply enlarge the current monthly graph, which is grouping results by 24 hours, so we'll simply see 2 big bars representing the 2 days we're interested into.

The ideal behavior would be to reload the data of those 2 days by leveraging the work that will be done in #26.
The expected result would be see something similar to the 3 day graph (many bars because results are grouped by 10-20 minutes), but it would happen by just zooming on the graph.

On the JS side, we'll have to bind to zoom events of the plotly library: https://plotly.com/javascript/zoom-events/
When a zoom event is fired, get the date range, and query the API to get that range accordingly.

Then we shall also implement sliding as discussed.

**Comment by yashikajotwani12** [comment]
**ToDos:**

1. **On zooming one year of data from [12th July to 17th July]** [Before]
![Screenshot from 2022-08-03 15-51-22](https://user-images.githubusercontent.com/77020164/182585715-28552370-d217-46e5-ade5-84c7b870d1e9.png)

     **Converted into a 7-day dateSpan Graph** [After]
![Screenshot from 2022-08-03 15-55-40](https://user-images.githubusercontent.com/77020164/182586294-535b945d-d3b8-4790-8020-c22f5333ee3b.png)
**IMP** :
     **This Zooming view to show data in contracted form would be temporary on refreshing or resetting the axis we would get the old data-time for the zoomed chart.**



2. **On sliding  left we want the previous data to load as we advance.**

    https://user-images.githubusercontent.com/77020164/182622713-ae6de6c0-d70f-4f4b-99bc-23ef9d8aba03.mp4

3. **We want this  sliding feature to happen with all the charts simultaneously.**

**Comment by yashikajotwani12** [comment]
Progress:

https://user-images.githubusercontent.com/77020164/183686412-a098b030-d78e-46e4-b46b-1992ef387423.mp4

**Comment by nemesisdesign** [comment]
> Progress:
> 
>  ScreenRecorder_2022-08-09_b1900e18-efb4-4cbd-bfd4-200404a73c3e.mp4

Nice :+1:, keep us posted.
