### ISSUE TITLE
[feature] Chart signal strength (LTE/UMTS/etc.)

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-monitoring#270]
Modem-manager interfaces are used for 3G/LTE routers and provide information regarding the protocols used in the mobile industry.

[OpenWISP Monitoring is already are able to collect information in the device status data](https://github.com/openwisp/openwisp-monitoring/commit/fb50d3dabbaf12fdc5b47f89a50507c2c0d25554) (please take an indepth look at this link), which is then displayed in the device status tab.

Now we need to add logic to the device metric view which is also able to log the signal strength (RSSI) information in a chart, as we already do for
the device charts.

The only difficult thing is that the RSSI value depends on the mobile protocol being used, because the router could be using
LTE, UMTS or other protocols depending on different factors.

**Key points:**

- only 3 charts
- each chart will have max 2 different lines shown
- the access technology chart does not use lines but bar color to indicate access technology used

**Signal strength chart:**

- RSRP (5G/4G) or RSCP (UMTS) can be labeled as Signal Power
- RSSI, which is available for 2G (GPRS), 3G (UMTS, EVDO, CDMA1X), 5G/4G can be labeled as Signal Strength

**Signal quality chart:**

- 4G and 5G SNR can be grouped under Signal to Noise Ratio (4G/5G SNR)
- 3G RSCP and 4G RSRQ can be grouped under Signal Quality (3G RSCP, 4G/5G RSRQ)

**Access technology chart:**

A fixed length bar chart (like reachability) indicating the access technology (GPRS, 3G, 4G, 5G, etc).

A color is associated to each number, but the user will be able to see the exact access technology when hovering with the mouse on the bar (this will help to clarify which specific access tech is used when there can be different ones for the same generation of mobile access tech, like in the  case of 3G)

We could use a color scale like the one below:

![Screenshot from 2021-04-16 20-06-52](https://user-images.githubusercontent.com/841044/116439309-05cc8080-a815-11eb-81d9-45a744f8f108.png)

Useful Resources:

- https://www.telcoantennas.com.au/blog/guide-to-mobile-networks/4g-lte-signal-strength-reference-guide/
- https://www.telcoantennas.com.au/blog/guide-to-mobile-networks/3g-umts-signal-strength-reference-guide/​

**Comment by Purhan** [comment]
I'm working on access technology chart but I'm not sure if my approach is good enough. I was thinking of using this query:
```python
    'access_tech': {
        'influxdb': (
            "SELECT MODE(access_tech) FROM {key} WHERE "
            "time >= '{time}' AND content_type = '{content_type}' AND "
            "object_id = '{object_id}' GROUP BY time(1d)"
        )
    },
```
Here, `MODE` will give us the most frequent access tech, but I'm not sure how practical this is.

**Comment by nemesisdesign** [comment]
> I'm working on the access technology chart but I'm not sure if my approach is good enough. I was thinking of using this query:
> 
> ```python
>     'access_tech': {
>         'influxdb': (
>             "SELECT MODE(access_tech) FROM {key} WHERE "
>             "time >= '{time}' AND content_type = '{content_type}' AND "
>             "object_id = '{object_id}' GROUP BY time(1d)"
>         )
>     },
> ```
> 
> Here, `MODE` will give us the most frequent access technology in a given time period, but I'm not sure how practical this is. What if there are 2 types of access methods being used simultaneously, which one do we consider in that case?

The device can work with only 1 access technology at time, but if there were switches from one to the other during the time period being grouped, I think we can show the one which was used most.
