### ISSUE TITLE
A small doubt regarding usage 

### ISSUE THREAD

**Issue by tusharmalpani20** [openwisp/openwisp-monitoring#277]
I have 5 routers flashed with OpenWRT and they are running a mesh network using B.A.T.M.A.N Adv.
When I went to topology there is a option called strategy which has 2 options fetch and receive. Am not sure what should be selected there and if I select receive where should I add that url link in my OpenWRT routers.
My apologies for asking such basic question.
Thanks in advance.

**Comment by okraits** [comment]
Please use the mailing list, forums or general chat for user questions. Thank you!
