### ISSUE TITLE
Typo in README in the CELERY section

### ISSUE THREAD

**Issue by apoulias** [openwisp/openwisp-monitoring#281]
Hello, 
After following the setup guide, I had an issue detecting devices going offline and noticed that in the section describing integration with existing django project, in the celery part, the guide states:
_'task': 'openwisp_monitoring.check.tasks.run_check'_ 
instead of 
_'task': 'openwisp_monitoring.check.tasks.run_check**s**'_.

**Comment by nemesisdesign** [comment]
Should be fixed (https://github.com/openwisp/openwisp-monitoring/commit/1b78b37b9e511db9029007111d1ddc2b97ba1a2b), thanks a lot for reporting @apoulias :+1:!
