### ISSUE TITLE
[monitoring] Refactor graph types: query should not be editable

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-monitoring#29]
Right now the query parameter of a chart (now called Graph) is editable via the django admin. This poses several issues: from UX (it's hard to deal with it) to security (the query could be manipulated to get data to which the user does not have access to). We need to refactor this part so that the user can choose among a predefined set of queries, but the list should be customizable using a django setting, so that users can implement their own queries if needed.

Maybe the `type` field of a Graph could indicate the query to run. Eg:

- uptime
- packet loss
- rtt
- histogram
- traffic
- wireless clients

This would also make the queries of the graphs easier to change, we could also provide settings that allow changing the chart style.

**Comment by nepython** [comment]
Closing it as it is identical to issue #47 which had been closed by #63. I didn't notice this issue earlier :sweat_smile:
