### ISSUE TITLE
[feature] Add REST API endpoints for device which include monitoring info

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-monitoring#290]
Extend the [REST API of OpenWISP Controller](https://github.com/openwisp/openwisp-controller/pull/386#pullrequestreview-628538950)  by adding two endpoints, one for the list of devices and one for the device detail.

- `/api/v1/monitoring/device/`: list devices and include the monitoring status
- `/api/v1/monitoring/device/{pk}/`: show device details, this endpoint already exists but only shows chart data and optionally device status data (if status=true is passed in the querystring). We need to add the following:
  - device information (as presented in OW controller API)
  - config info (as presented in OW controller API)
  - main health status of the device 
  - a list of metrics with their respective status (this is needed when there's a problem to understand which metric is not healthy)

We need to allow accessing this info by using the user auth token (now only device key can access it), however only the authentication with the device key should be able to post monitoring data, because that's reserved for devices.

**Comment by Saurav-Shrivastav** [comment]
For the endpoint `/api/v1/monitoring/device/{pk}/`, should the `GET` requests work without a device key and only rely on the user token or the user token should also be required along with the device key?

**Comment by ManishShah120** [comment]
Hi @Saurav-Shrivastav for a `GET` request user token will do, but the endpoint should not allow `POST` request without the  authentication with the device key,

**Comment by Manjuphoenix** [comment]
Hey @nemesisdesign is this issue still there?
I would like to work on this, can you assign me to this particular issue?

**Comment by Manjuphoenix** [comment]
@nemesisdesign In the below picture i could see just 3 API's with predefined key values passed, if given more details regarding the different devices i can create API's for the same
![API's_list](https://user-images.githubusercontent.com/56871357/142750696-291d4bbe-1a21-4321-9e09-46b8a4828ca5.png)

**Comment by nemesisdesign** [comment]
@Manjuphoenix I do not understand your questions, I think the issue description has enough details, if something is not clear, please ask a more specific question like @Saurav-Shrivastav did.

Anybody: you're free to work on this issue if you want, just let us know and send a PR.

Join https://gitter.im/openwisp/development if you need help.

**Comment by uzaxirr** [comment]
Hey @nemesisdesign !! 
This is still open correct? I'll start working on it soon after the confirmation!

**Comment by Aryamanz29** [comment]
Hey @uzaxirr! There is already a `draft PR` opened for this issue, #480, but I have put this work on hold because I have some queries regarding the API design that need to be clarified first before proceeding further. I would suggest you check `"good first issues"` on the [OpenWISP Contributor's Board](https://github.com/orgs/openwisp/projects/3.), thanks!
