### ISSUE TITLE
Non-superusers can not access the notification page

### ISSUE THREAD

**Issue by lehone-hp** [openwisp/openwisp-monitoring#3]
Whenever a user without superuser privileges tried to access the notification page by clicking on the bell icon at the top right of the home page, a **403 Forbidden** error page is returned. 
My guess is the permissions to access notification are are not assigned to normal users during registration.

**Comment by nemesisdesign** [comment]
I think the default permissions need to be added to the operator and administrator groups, like we do in other modules.
