### ISSUE TITLE
[monitoring] Allow to store IP addresses of interfaces in DeviceData.data

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-monitoring#30]
The device status information (accessible via `DeviceData.data`) stores information about the current status of the device (uptime, memory usage, load averages).

When the device has interfaces (eg LAN or WAN) set in DHCP client mode, there's no way to easily know which address the device got from the DHCP server.

This aims to fix that.

Incoming payoad example:
```
{
    'type': 'DeviceMonitoring',
    'interfaces': [
        {
            'name': 'br-lan',
            'addresses': [
                {
                    'proto': 'static',
                    'family': 'ipv4',
                    'address': '192.168.1.1',
                    'mask': 24
                },
                {
                    'proto': 'dhcp',
                    'family': 'ipv4',
                    'address': '10.0.0.4',
                    'mask': 24
                }
            ]
        }
    }
}
```

The schema in `openwisp_monitoring.device.schema` will have to be updated to include the addresses schema: http://netjson.org/rfc.html#addresses1
The gateway option can be ignored.

If we get a non-wireless interface without any address, we will not store it for now (wireless interfaces are stored anyway, they contain other useful info related to the wireless settings).

Once the data is saved and validated correctly (a few tests will need to ensure bogus addresses will be rejected) we will have to ensure the ip addresses of each interface are shown in the device status tab:
https://github.com/openwisp/openwisp-monitoring/blob/master/openwisp_monitoring/device/templates/admin/config/device/change_form.html#L66-L124

Will require https://github.com/openwisp/lua-monitoring/issues/1 to be complete.

**Comment by nepython** [comment]
I am working on it :smiley:

**Comment by nemesisdesign** [comment]
@nepython do you already have an openwrt device or VM? Coordinate on the gitter channel with @NoumbissiValere and @PabloCastellano, they already have done similar things.

**Comment by nepython** [comment]
>@nepython do you already have an openwrt device or VM? 

No, I don't have an openwrt device currently but I have setup a VM (though I need to configure it correctly).
Is it essential for this PR, if so then I will proceed with configuring it.
> Coordinate on the gitter channel with @NoumbissiValere and @PabloCastellano, they already have done similar things.

Sure :smile:

**Comment by nepython** [comment]
>When the device has interfaces (eg LAN or WAN) set in DHCP client mode, there's no way to easily know which address the device got from the DHCP server.

@nemesisdesign, can you please give few details on how the `addresses` need to be refactored to easily retrieve them later. Should I do something similar to what has been done for `uptime`.
https://github.com/openwisp/openwisp-monitoring/blob/4d96d743e0e583ba10445b08d2ed34b18d1be45a/openwisp_monitoring/device/models.py#L55-L57
I have created a draft PR [here](https://github.com/openwisp/openwisp-monitoring/pull/64). I am still working on it, created it for reference.

**Comment by nemesisdesign** [comment]
@nepython just loop over the addresses and show them in a table, eg:

``
address          |   mask      |   DHCP client?  
192.168.1.2    |  /{mask}   |   yes / no
```

The difficult part may be to get the correct `mask`, but we'll deal with that on the openwrt side.
