### ISSUE TITLE
[refactoring] Migrate from Popen() to run()

### ISSUE THREAD

**Issue by nickberry17** [openwisp/openwisp-monitoring#300]
From the [Python docs](https://docs.python.org/3/library/subprocess.html#using-the-subprocess-module)
> The recommended approach to invoking subprocesses is to use the `run()` function for all use cases it can handle. For more advanced use cases, the underlying Popen interface can be used directly.
> 
> The run() function was added in Python 3.5; if you need to retain compatibility with older versions, see the Older high-level API section.

Is this an "advanced use case"?  Should we consider migrating to `run()`?

https://github.com/openwisp/openwisp-monitoring/blob/1b78b37b9e511db9029007111d1ddc2b97ba1a2b/openwisp_monitoring/check/classes/ping.py#L140

**Comment by nemesisdesign** [comment]
@nickberry17 I'm not such in a hurry to change it, but should be just a 2 line change: https://github.com/openwisp/openwisp-monitoring/blob/1b78b37b9e511db9029007111d1ddc2b97ba1a2b/openwisp_monitoring/check/classes/ping.py#L140-L141
Initially this module supported also python2 but now we should be able to simplify that.

**Comment by Aryamanz29** [comment]
I would like to work on this
