### ISSUE TITLE
[change] Reachable bar chart: show different color for barely reachable

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-monitoring#301]
When reachability is higher than 0% but not yet to the right percentage level to show the yellow color, the color stays red, but this is problematic because at glance it looks like the device is still down while it may have just started to show as reachable.

Therefore we'll need to make sure the color shown is a bit different (dark orange?). 

The same is true for a device which is >90% reachable, I think it would be good to use a different shade of green.

**Comment by atb00ker** [comment]
How about a dark grey color for non-reachable device and red for low %.
Red for completely unreachable and blue for low %.
Or 
Red for completely unreachable and red with yellow strips for low %.


Having completely different colors or strips will ensure that someone with slight color blindness can also distinguish easily. 😄

**Comment by yashikajotwani12** [comment]
Hey @nemesisdesign, I have one doubt that do we need to mention barely reachable like this :
![Screenshot (4)](https://user-images.githubusercontent.com/77020164/162949554-79b295b7-b1bd-43b4-9d3a-ed35fcf9dd94.png)
Or 
We need  `dark orange color` only to show when the device is barely reachable and not to mention here.

**Comment by nemesisdesign** [comment]
> Hey @nemesisdesign, I have one doubt that do we need to mention barely reachable like this : ![Screenshot (4)](https://user-images.githubusercontent.com/77020164/162949554-79b295b7-b1bd-43b4-9d3a-ed35fcf9dd94.png) Or We need `dark orange color` only to show when the device is barely reachable and not to mention here.

@yashikajotwani12: we can name it "Mostly unreachable" and it can be of dark orange color like that, including it in the legend.

We also need to add **"Mostly reachable"** if it's more than 90% but less than 99%. I would use the current reachable color for "Mostly reachable" and change the Reachable color to a darker green. I will improve the colors if needed in the end.

**Comment by yashikajotwani12** [comment]
> > Hey @nemesisdesign, I have one doubt that do we need to mention barely reachable like this : ![Screenshot (4)](https://user-images.githubusercontent.com/77020164/162949554-79b295b7-b1bd-43b4-9d3a-ed35fcf9dd94.png) Or We need `dark orange color` only to show when the device is barely reachable and not to mention here.
> 
> @yashikajotwani12: we can name it "Mostly unreachable" and it can be of dark orange color like that, including it in the legend.
> 
> We also need to add **"Mostly reachable"** if it's more than 90% but less than 99%. I would use the current reachable color for "Mostly reachable" and change the Reachable color to a darker green. I will improve the colors if needed in the end.

Thank you @nemesisdesign! I understood everything would work accordingly.
