### ISSUE TITLE
[monitoring] Move get_device_data logic to DeviceData model

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-monitoring#31]
Move the [admin method get_device_data](https://github.com/openwisp/openwisp-monitoring/blob/master/openwisp_monitoring/device/admin.py#L20-L53) to the `DeviceData` model, calling it `data_user_friendly` (decorate it as a `@property`).

The reason for this change is that we will serve the same content also via other views and hence it makes sense to make this accessible via the model, so views will only have to call the model method.

**Comment by PabloCastellano** [comment]
I'm working on it
