### ISSUE TITLE
Can change the configuration of the access point, but the health status is always critical

### ISSUE THREAD

**Issue by tranvanhoa533** [openwisp/openwisp-monitoring#314]
The access point successfully connects to openwisp and can change its configuration at any time, but the health status is always critical. Can you help me get the right health status of the access point. Thank you very much.

**Comment by nemesisdesign** [comment]
This is a bug tracker. Please use the [support channels](https://openwisp.org/support.html). I suggest sending an email to the [OpenWISP Mailing List](https://groups.google.com/d/forum/openwisp/join).
