### ISSUE TITLE
[deps] Add support for django 3.2 and django 4.0 alpha

### ISSUE THREAD

**Issue by codesankalp** [openwisp/openwisp-monitoring#322]
Let's make sure this module can run with Django 3.2 and Django 4.0 alpha.

**Comment by ashutosh887** [comment]
I would like to take this up @codesankalp

**Comment by Aryamanz29** [comment]
@codesankalp How to proceed with this issue? Could you please guide

**Comment by codesankalp** [comment]
> @codesankalp How to proceed with this issue? Could you please guide

Try testing openwisp-monitoring for different versions of Django as mentioned in the issue heading and if some issue arises while testing, fix them.
 See https://github.com/openwisp/openwisp-utils/pull/258 for reference.

**Comment by pandafy** [comment]
Hey @Aryamanz29! Are you still working on this?

**Comment by Aryamanz29** [comment]
> Hey @Aryamanz29! Are you still working on this? 

 Yes @pandafy , I'll be raise PR soon.
