### ISSUE TITLE
[bug] Celery beat schedule file gets corrupted

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-monitoring#325]
I've been observing an issue with celery which gets its schedule file corrupted and starts breaking:

```
[2021-10-16 00:28:14,729: WARNING/MainProcess] self.dict[key.encode(self.keyencoding)] = f.getvalue()
[2021-10-16 00:28:14,729: WARNING/MainProcess] _dbm
[2021-10-16 00:28:14,729: WARNING/MainProcess] .
[2021-10-16 00:28:14,730: WARNING/MainProcess] error
[2021-10-16 00:28:14,730: WARNING/MainProcess] :
[2021-10-16 00:28:14,730: WARNING/MainProcess] cannot add item to database
```

It won't restart unless the schedule file is removed, but the problem may happen again on its own after a few days.

It may be a bug with celery, let's find out.

**Comment by pandafy** [comment]
I investigated this. Some other projects also faced this issue. 

This project also suffered from this issue multiple times and for them installing python3-gdbm worked. https://github.com/WeblateOrg/weblate/issues/2730#issuecomment-490569287

**Comment by nemesisdesign** [comment]
It keeps on happening. It seems to me it happens after upgrades.

**Comment by nemesisdesign** [comment]
We have to try Celery 5, if it happens also with Celery 5 we'll have to add a watchdog script in cron to ansible-openwisp2 which checks every minute whether celery beat is running and if not it checks the log to see whether this error is present in the last 50 lines and if it is it deletes the schedule file and starts celery.

**Comment by nemesisdesign** [comment]
Since the introduction of https://github.com/openwisp/ansible-openwisp2/pull/318 I haven't seen this issue anymore.
