### ISSUE TITLE
[bug] homepage pie charts not centered on mobile

### ISSUE THREAD

**Issue by minhng99** [openwisp/openwisp-monitoring#326]
I don't think it's supposed to looks like this?

![Screenshot_20211023-143425_Chrome](https://user-images.githubusercontent.com/14113155/138547359-3a418e11-d89d-4a0d-a8d4-0ad77ba64592.jpg)

**Comment by Aryamanz29** [comment]
I would like to work on this

**Comment by nemesisdesign** [comment]
Resolved by https://github.com/openwisp/openwisp-utils/issues/275. Thanks @Aryamanz29 :+1:
