### ISSUE TITLE
[bug] Migrations depend on unswappable openwisp modules

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-monitoring#327]
Similar to https://github.com/openwisp/openwisp-controller/issues/565.

There's unswappable migration dependencies to:

- openwisp-notifications
- openwisp-controller
- `migrations.swappable_dependency(settings.AUTH_USER_MODEL)` should be changed to the new form we're using in openwisp-radius (`swapper.dependency(*swapper.split(settings.AUTH_USER_MODEL), latest=True)`)

**Comment by yashikajotwani12** [comment]
I would like to work on this.
