### ISSUE TITLE
netjson-monitoring error index a nil value, related to hostapd

### ISSUE THREAD

**Issue by jamalhill4sure** [openwisp/openwisp-monitoring#332]
got this error on tplink re220

root@tplink84271:~#
login as: root
root@192.168.1.1's password:

BusyBox v1.33.1 (2021-10-24 09:01:35 UTC) built-in shell (ash)

  _______                     ________        __
 |       |.-----.-----.-----.|  |  |  |.----.|  |_
 |   -   ||  _  |  -__|     ||  |  |  ||   _||   _|
 |_______||   __|_____|__|__||________||__|  |____|
          |__| W I R E L E S S   F R E E D O M
 -----------------------------------------------------
 OpenWrt 21.02.1, r16325-88151b8303
 -----------------------------------------------------
root@tplink84271:~# /usr/sbin/openwisp-monitoring
lua: /usr/sbin/netjson-monitoring:451: attempt to index a nil value
stack traceback:
        /usr/sbin/netjson-monitoring:451: in main chunk
        [C]: ?
Note: Unnecessary use of -X or --request, POST is already inferred.
> POST /api/v1/monitoring/device/ REDACTED
> User-Agent: curl/7.79.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 0
>
< HTTP/1.1 400 Bad Request
< Server: nginx/1.18.0 (Ubuntu)
< Date: Thu, 30 Dec 2021 23:02:55 GMT
< Content-Type: application/json
< Content-Length: 73
< Connection: keep-alive
< Vary: Accept, Cookie
< Allow: GET, POST, HEAD, OPTIONS
< X-Frame-Options: DENY
< X-Content-Type-Options: nosniff
< Referrer-Policy: same-origin
<
"Invalid data in \"#/\", validator says:\n\nNone is not of type 'object'"root@tplink84271:~#
root@tplink84271:~#

root@tplink84271:~# opkg list-installed | grep openwisp
openwisp-config-openssl - 0.6.0a-1
root@tplink84271:~#

**Comment by nemesisdesign** [comment]
Please try the latest version of the agent and this module, if it still happens, reopen the issue.
