### ISSUE TITLE
[bug] Task trigger_device_checks triggering a lot of unnecessary network checks

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-monitoring#338]
The task `trigger_device_checks` is called when checksum and monitoring data is received, which happens all the time.
Then this code is executed in the background:

https://github.com/openwisp/openwisp-monitoring/blob/bdcfff2b17468278ec161b4b31b64ea67a6869fb/openwisp_monitoring/device/tasks.py#L12-L33

The point of this feature is to quickly find out if a device has come back online after it wasn't.
But the code doesn't take into account that if a device is already ok it should not repeat the checks.

So if there's 1000 devices online, not only the monitoring worker will do 1000 checks every 5 minutes, but it will do a lot more because every 5 minutes there's at least 1 metric sending and 2 checksum requests, so every 5 minutes the system will do 4000 checks.

If my analysis is correct, this is a problem.

So first of all we should check whether the analysis is correct, then I think we can join the device data with DeviceMonitoring (so we keep doing one query to retrieve the device, but will fetch the health status as well), then check whether the health status is ok and in that case I think we can just return.

**Comment by pandafy** [comment]
> The task trigger_device_checks is called when checksum and monitoring data is received, which happens all the time.

This scenario is already handled by https://github.com/openwisp/openwisp-monitoring/blob/dedc4a913004e019a74eef6fcb64647ecdf31114/openwisp_monitoring/device/apps.py#L93-L102. 

I have opened #339 to add tests that explicitly tests this.
