### ISSUE TITLE
[change] Remove charts which have empty data

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-monitoring#349]
- [ ] In the API which returns the charts of a device, if the data is empty, there's no need to include the chart in the response.
- [ ] We shall make sure the chart is not shown in the UI

**Comment by proshee** [comment]
when i run the command python manage.py migrate,
it shows
File "/Users/tanujchandela/Documents/git/Contribution/venv/openwisp-monitoring/tests/openwisp2/init.py", line 3, in <module>
from .celery import app as celery_app
File "/Users/tanujchandela/Documents/git/Contribution/venv/openwisp-monitoring/tests/openwisp2/celery.py", line 5, in <module>
from celery import Celery
ModuleNotFoundError: No module named 'celery'
but i have installed celery
(base) tanujchandela@Tanujs-MacBook-Air tests % pip show celery
Name: celery
Version: 5.2.3
Summary: Distributed Task Queue.
Home-page: http://celeryproject.org
Author: Ask Solem
Author-email: auvipy@gmail.com
License: BSD
Location: /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages
Requires: billiard, click, click-didyoumean, click-plugins, click-repl, kombu, pytz, setuptools, vine
Required-by: openwisp-controller, openwisp-notifications
please help me with this issue

**Comment by n1snt** [comment]
Can I take this issue?
