### ISSUE TITLE
[change] Change look of traffic charts

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-monitoring#366]
I want to change the look of the current traffic charts to look like the following:

![traffic-complete](https://user-images.githubusercontent.com/841044/164270524-7eedaa0b-0e7a-4dd4-b84e-730d99503889.png)

With this new configuration, we can show at glance the upload, download and total.

A prototype can be seen in action here, it can be also exported as HTML, which will contain the JS code for plotly:
https://chart-studio.plotly.com/~nemesisdev/1

**Comment by Aryamanz29** [comment]
Hey @nemesisdesign, I've tried many times downloading this prototype code but always getting `server error`. Could you please confirm?
![Screenshot from 2022-05-05 02-18-31](https://user-images.githubusercontent.com/56113566/166823771-7db06591-b9a8-46e2-947e-e7b68bc9aad1.png)

**Comment by nemesisdesign** [comment]
> Hey @nemesisdesign, I've tried many times downloading this prototype code but always getting `server error`. Could you please confirm? ![Screenshot from 2022-05-05 02-18-31](https://user-images.githubusercontent.com/56113566/166823771-7db06591-b9a8-46e2-947e-e7b68bc9aad1.png)

I don't have issues in exporting it, have you tried using the export button? I also sent it to you via email.

**Comment by yashikajotwani12** [comment]
Hey @Aryamanz29 are you working on this?

**Comment by Aryamanz29** [comment]
> Hey @Aryamanz29 are you working on this?

Not yet, You can take this 👍
