### ISSUE TITLE
[feature] Make Iperf3 check resilient to failures

### ISSUE THREAD

**Issue by Aryamanz29** [openwisp/openwisp-monitoring#389]
- If any failures or server down, We must handle that situation & may store some value to timeseries database, let say 0.
   - Using `exit_code` of executed commands on device we can handle this case (To-do: Need to explore better option for this)

```py
    res, exit_code = device_connection.connector_instance.exec_command(
                command, raise_unexpected_exit=False
            )
        if exit_code != 0:
                ## command_exec fails
                if store:
                    self.store_result(
                        {
                            'iperf_result': 0,
                            'sum_sent_bps': 0.0,
                            'sum_rec_bps': 0.0
                            ...
                            ...
                        }
```
- It should trigger an alert for respective failures.

**Comment by pandafy** [comment]
> * Using `exit_code` of executed commands on device we can handle this case (To-do: Need to explore better option for this)

Can you please explain what needs to be explored here? It is not clear to me? `exit_code` of the executed command should suffice the purpose here. Do you see any shortcoming with that?

**Comment by Aryamanz29** [comment]
Solved and Closed by : https://github.com/openwisp/openwisp-monitoring/pull/447
