### ISSUE TITLE
[feature] Listen to DeviceConnection.is_working changes 

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-monitoring#4]
To be done after: https://github.com/openwisp/openwisp-controller/issues/174

This is an idea/draft, the whole flow should be revisited and improved.

Listen to the `DeviceConnection.is_working` change signal and perform the following operations:

- if the device connection has switched from working to not working:
  - set the device monitoring status to `PROBLEM`
  - create a related notification, include the information about why the connection is not working
  - if the monitoring status was set to `OK` (before we set it to problem) we should find out if there's any check existing for this device, if yes, trigger the checks (will be run in the background by celery)
- if the device connection has switched from not working to working
  - create a related notification
  - if there's any check related to this device, trigger the checks, if there's no available check, set the monitoring status to OK

**Comment by nepython** [comment]
Working on it :smile:
