### ISSUE TITLE
[feature] Possibility to add alerts for related_fields

### ISSUE THREAD

**Issue by Aryamanz29** [openwisp/openwisp-monitoring#406]
- If we look at current implementation of alerts, We see that alerts checks thresholds on only `value/field_name`, it would be nice if we can add alert functionality for `extra_values/related_fields` as well.
https://github.com/openwisp/openwisp-monitoring/blob/6119ac0dfa7221e7e06d88fdcd628ec0d629a3a7/openwisp_monitoring/monitoring/base/models.py#L315-L358

**Comment by nemesisdesign** [comment]
> * If we look at current implementation of alerts, We see that alerts checks thresholds on only `value/field_name`, it would be nice if we can add alert functionality for `extra_values/related_fields` as well.
>   https://github.com/openwisp/openwisp-monitoring/blob/6119ac0dfa7221e7e06d88fdcd628ec0d629a3a7/openwisp_monitoring/monitoring/base/models.py#L315-L358

We need this for the Iperf alerts right? If so, we can look for a solution, do you have any idea?

**Comment by Aryamanz29** [comment]
> We need this for the Iperf alerts right? If so, we can look for a solution, do you have any idea?
Yes, It would be great If we can add alerts on `related_fields` because my `iperf` configuration currently look like this :
https://github.com/openwisp/openwisp-monitoring/blob/issue-385/iperf-check/openwisp_monitoring/monitoring/configuration.py#L546-L650
