### ISSUE TITLE
[enhancement] Introduce the concept of metric type/class/configuration

### ISSUE THREAD

**Issue by nepython** [openwisp/openwisp-monitoring#44]
**Info about metric model**:
The Metric model allows to store different aspects of a metric, for example, the ping metric allows to store the `reachable` result (1 for reachable and 0 for unreachable), the packet loss and the round trip information (rtt_min, rtt_max and rtt_average).

**The Problem**:
Each aspect is stored with a different key in the same metric object of the timeseries DB, but the django model does not show this information and this makes some operations harder (eg: automatically creating charts which uses some or all the aspects of the metric).

**Possible Solution**: 
Introduce the concept of a metric type and have this kind of general information stored on the metric type, provided metric types are extensible and users can define their own types.
~~This could [help](https://github.com/bitlabstudio/django-influxdb-metrics)~~

**Comment by nemesisdesign** [comment]
Pasting here what I wrote on gitter.

Metric is a mapping between what we have in the primary DB (used by django/openwisp) and the timeseries DB.
It allows us to link the data between the two databases.

Do you remember how graphs where implemented? Their parameters were scattered around the codebase. Now they're all centralized in one place. To add a new graph, we can do it by editing one data structure.
We should do the same for metric types.

From the configuration, we must know if the keys used are all known or not.
In most cases they are, so we should list them in the configuration.
it's like what @pandafy is doing with notification types: openwisp/openwisp-notifications#19
