### ISSUE TITLE
[docs] Mention custom date range usage in `List of endpoints` section

### ISSUE THREAD

**Issue by Aryamanz29** [openwisp/openwisp-monitoring#453]
We recently added a date range widget to the project, which updates existing API endpoints (General & Device charts), so we need to update the [List of endpoints](https://github.com/openwisp/openwisp-monitoring#list-of-endpoints) section of the docs.

**Comment by kishan3** [comment]
Can you tell what to add in the doc? I will be working on it. Thanks

**Comment by Aryamanz29** [comment]
Hey, @kishan3 Thanks for showing interest in this issue but this one is connected to the [feature](https://github.com/openwisp/openwisp-monitoring/commit/c6700bc76cd2aed1ab5d112bb4e02fe802248b41) that we recently introduced to our project. If you're looking for some `hactoberfest/good-first-issues`[ here is the list](https://github.com/openwisp/openwisp-utils/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3AHacktoberfest) 😄

**Comment by kishan3** [comment]
Thanks
