### ISSUE TITLE
[change] Find faster way to write to influxdb (eg: UDP)

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-monitoring#458]
We should find a faster method for writing timeseries data, maybe UDP instead of HTTP.
I think this may change from influxdb 1.8 to 2.0 so we'd have to check this on Influxdb 2.0 #274.
Right now writing timeseries on big systems is quite a bottleneck!

See also https://github.com/openwisp/openwisp-monitoring/issues/466.

**Comment by pandafy** [comment]
The `influxdb-python` library [supports connecting to InfluxDB using UDP](https://influxdb-python.readthedocs.io/en/latest/api-documentation.html#api-documentation-1).

We need to verify that the authentication works with UDP.
