### ISSUE TITLE
[enhancement] Renaming the models Threshold and Graph in a backward compatible manner

### ISSUE THREAD

**Issue by nepython** [openwisp/openwisp-monitoring#46]
Rename the models which are now called `Threshold`, `Graph` to `AlertSettings`, `Chart` respectively, in a backward compatible way (eg: provide a data migration which creates the alert table first, copies the data from the threshold table into alert and then remove the old threshold table, or an equivalently working alternative).

**Comment by PabloCastellano** [comment]
Just as a side note for the backwards-compatible part, Django migrations support renaming models/tables.

**Comment by nepython** [comment]
@PabloCastellano, I forgot to share a mailing list thread. I noted the same [here](https://groups.google.com/d/msg/openwisp/tinsyzJt3BE/3VazszdaAwAJ)

**Comment by PabloCastellano** [comment]
Since Django 2.0 was released on 2nd December 2017 and the first commit in this repo came 2 months later, I think it's safe to assume that everyone using this module is using Django 2.0+ no there's no need to take extra caution

**Comment by nemesisdesign** [comment]
> Since Django 2.0 was released on 2nd December 2017 and the first commit in this repo came 2 months later, I think it's safe to assume that everyone using this module is using Django 2.0+ no there's no need to take extra caution

:+1:
