### ISSUE TITLE
[bug] Map is bound and borders bounce

### ISSUE THREAD

**Issue by nemesifier** [openwisp/openwisp-monitoring#462]
It seems that dragging the map from Asia/Oceania to the Americas and vice versa is not permitted, which is very uncomfortable:

![map-bug](https://user-images.githubusercontent.com/841044/202294308-cc047b7d-c989-4a8b-824d-c2fb234f90ae.gif)

Any leaflet demo doesn't show this issue: https://leafletjs.com/examples/geojson/

Looking at the django-leaflet code in the dashboard I see:

```
"extent": [[-90, -180], [90, 180]], "fitextent": true
```

I wonder if this is what is causing this bounce?

**Comment by nemesisdesign** [comment]
This should be fixed if we complete https://github.com/openwisp/openwisp-monitoring/issues/393 .

**Comment by nemesifier** [comment]
Solved by #433.
