### ISSUE TITLE
Server Error (500) Openwisp-Monitoring version commit on Nov 20, 2022

### ISSUE THREAD

**Issue by desolated40** [openwisp/openwisp-monitoring#464]
Not sure if this is know already but after updating Openwisp-Monitoring to the development version committed on Nov 20, 2022 the devices and configuration > VPN servers page shows "Server error 500".

Although at the Home page the Current Active WiFi sessions, General WiFi Clients and General Traffic the values are shown correctly.

**Comment by nemesisdesign** [comment]
I am closing this for the following reasons:

- cannot replicate it
- not enough technical information on how to replicate the issue (which version? how did you deploy, ansible, docker, manually, is this a dev env or a prod env? Etc)
- not the right repo, VPN servers page is from openwisp-controller (I could move the issue if it was valid)
