### ISSUE TITLE
[enhancement] Refactor the query parameter of Chart

### ISSUE THREAD

**Issue by nepython** [openwisp/openwisp-monitoring#47]
This is an **idea/draft** and needs more refining, few details also need to be added.

**The Need**
The query parameter of a chart (now called Graph) is editable via the django admin. This poses several issues: from UX (it's hard to deal with it) to security (the query could be manipulated to get data to which the user does not have access to).

This needs to be refactored so that the user can choose among a predefined set of queries from a list.

The list should be customizable using a django setting, so that users can implement their own queries if needed. Add documentation about this setting explaining how to customize it.

**Details missing** :
What all queries should be added in the list by default?
What would be the best location to define the base list from in the `monitoring` app. Currently, I am thinking of `utils.py`

**Comment by nemesisdesign** [comment]
> Details missing :
> What all queries should be added in the list by default?
> What would be the best location to define the base list from in the monitoring app. Currently, I am thinking of utils.py

All the graphs currently supported: bandiwdth, wifi clients, uptime, packet loss, rtt, histograms.

I will work on improving the definition of this issue during this week. There's a chance I may be doing part of it to help you understand, and also to help to clean the mess I have created in the first place :blush:
