### ISSUE TITLE
[change] Add timeout to all celery tasks

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-monitoring#474]
Let's ensure all tasks have a reasonable timeout.

Some tasks like `run_checks` must have a higher timeout (eg: 1 hour), we should avoid hitting this under all conditions, all the other tasks should have much shorter timeout but not too short.

**Comment by uzaxirr** [comment]
Hey, Can i take this up?
My approach would be adding `CELERYD_TASK_SOFT_TIME_LIMIT` configuration option in celery configuration file. However can you please specify what should be the timeout value

**Comment by pandafy** [comment]
Hey @uzaxirr! This is a delicate change which requires prior experience with OpenWISP. I ask you to check "good first issues" on [OpenWISP Contributors Board]((https://github.com/orgs/openwisp/projects/3).
