### ISSUE TITLE
SynchronousOnlyOperation from celery task using gevent execution pool on django orm

### ISSUE THREAD

**Issue by zN3utr4l** [openwisp/openwisp-monitoring#518]
Hi, this is not a question about your package but about a similar problem which I think you have solved.

I'm talking about the gevent and celery problem, I haven't found answers in any forum, neither django, nor anyone else, it seems to me that you have gone back from using gevent or "`fix_async(lambda: check.perform_check())`"

does it work for you?

https://github.com/openwisp/openwisp-monitoring/pull/257

**Comment by nemesisdesign** [comment]
We went back to using prefork. Using gevent will require a careful overhaul of the code used in background tasks to make it play well with async.
