### ISSUE TITLE
Ping Issue

### ISSUE THREAD

**Issue by lfdominguez-servinfo** [openwisp/openwisp-monitoring#519]
Hi, I am on the design phase of my deployment project of wifi routers and choose OpenWISP as central controller. I was testing it but i found a simple problem, my routers will be on nodes where the input connection will be dropped, only allow output connections, to reconfigure is not a problem because the openwisp client of openwrt connect to the central server, but OpenWISP use a simple ping to check if the router is alive. There is something in OpenWISP that allow to do a "reverse Ping", something like.... If the wifi router not contact in 2 times the client refresh time then set as down. Thanks for the good project

**Comment by nemesifier** [comment]
Such a feature is not available. In most deployments a management tunnel is needed for troubleshooting unless there's already a network in place (L2,  which allow the server to reach the devices. Not having a management tunnel is not recommended.
