### ISSUE TITLE
[enhancement] Export histogram chart data

### ISSUE THREAD

**Issue by nepython** [openwisp/openwisp-monitoring#56]
Add a possibility of exporting data of `Histogram` charts.

**QUERY**:
* What is the problem currently?
* Why can't it be done similarly as `scatter` and `bar` charts?

**Comment by PabloCastellano** [comment]
The actual problem is that exporting the data in CSV format does not export the histograms data.

Check out the generated csv file. The rows show time intervals. Since histograms don't have a time interval, they are not exported.
