### ISSUE TITLE
ERROR: pip's dependency resolver

### ISSUE THREAD

**Issue by VshadowTX** [openwisp/openwisp-monitoring#582]
Not uninstalling jinja2 at /usr/lib/python3/dist-packages, outside environment /usr
    Can't uninstall 'Jinja2'. No files were found to uninstall.
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
mkdocs 1.4.2 requires markdown<3.4,>=3.2.1, but you have markdown 3.4.4 which is incompatible.

**Comment by nemesifier** [comment]
Hi @VshadowTX,

I'm closing this issue as it doesn't contain enough information to be considered a valid bug report.

If you believe there is a bug, please open a new issue and provide detailed steps to replicate it, starting from this repository or including the documented installation process you followed. Adding more context will help us better understand the issue.

For any other questions that are not related to bug reports, please use one of our [support channels](https://openwisp.org/support.html).

Thank you!
