### ISSUE TITLE
[enhancement] Abstract code communicating with the time series DB

### ISSUE THREAD

**Issue by nepython** [openwisp/openwisp-monitoring#65]
Abstract the code that communicates with the timeseries DB so that new timeseries backends can be written to support other timeseries DBs.

* All the operations that are done with the timeseries DB are to be abstracted in a class, which we'll call timeseries DB backend.
* All queries and lines of code scattered around openwisp-monitoring which produce requests to influxdb have to be centralized in a class called timeseries DB backend.
* There must be a setting which allows configuring which backend to use, like django does with the SQL databases.

**Comment by nepython** [comment]
I am thinking of separating all the queries and calling the same from a dictionary. The dictionary will contain the queries for both the timeseries which shall make it easier to use across the module. This will organize all the queries in one **dict** object but it will also result in the code of many objects getting scattered (example, **DEFAULT_CHARTS**). This might not be a good way to do it but I can't think of any other way. So is this correct or there is some better way to do it?

**Comment by PabloCastellano** [comment]
@nepython The approach looks good to me

**Comment by nepython** [comment]
> @nepython The approach looks good to me

@PabloCastellano, #103 should give you a better view of how I was thinking of implementing it.
Please have a look :smile:
