### ISSUE TITLE
[docs] Update README

### ISSUE THREAD

**Issue by nepython** [openwisp/openwisp-monitoring#70]
Ensure the `README` is up to date, lists all the features available, provides some `screenshots` and a detailed explaination of the usage of the main features added in this project.

### Things to be documented:
* [ ] Badges as other OpenWISP modules
* [ ] `run_checks` command (maybe something similar to https://github.com/openwisp/django-freeradius/blob/master/docs/source/general/management_commands.rst)
* [ ] Signals Missing:
 * pre_metric_write
 * post_metric_write
 * health_status_changed
* [ ] Images (`AlertSettings Inline`, `Checks Inline`, `Metric Health`) and GIF need to be updated as per latest changes.
* [ ] Reference to `OPENWISP_MONITORING_DEVICE_CONFIG_CHECK_MAX_TIME` setting needs to be removed from https://github.com/openwisp/openwisp-monitoring/tree/dev#configuration-applied (somehow missed to notice it until now :/).

**Comment by nepython** [comment]
I will surely document as I introduce the changes but this issue is for updating the **README** to make it more effective for the end-user to understand the module :smile:

**Comment by nemesisdesign** [comment]
Let's coordinate with @atb00ker since he's been doing this for different modules and we've been experimenting with animated gifs which seem a great way to show what the module can do at glance.

@pandafy related to you as well :point_up:

**Comment by atb00ker** [comment]
My workflow for creating the GIFs, 
1. List all the features in order that I want to show them in the video.
2. Do some demo runs to ensure that GIF is as short as possible in the final shot.
3. Use Firefox, because F11 takes you to full screenwithout any borders.
4. Use `simplescreenrecorder` recording `mkv` in full screen at 7 FPS
5. Convert mkv to an efficient GIF: 
```
ffmpeg -i  vid.mkv -vf fps=7,scale=1366:-1:flags=lanczos,palettegen palette.png
ffmpeg -i vid.mkv -i palette.png -filter_complex "fps=7,scale=1366:-1:flags=lanczos[x];[x][1:v]paletteuse" demo.gif
```

6. Use https://ezgif.com/optimize to optimize further according to requirement.
7. If the size is still big, some steps specific to the GIF may be required.

**Comment by atb00ker** [comment]
@nepython @pandafy , let me know if you need any further assistance with creating GIFs! :smile:

**Comment by nepython** [comment]
Thanks, @atb00ker :smiley:

**Comment by nemesisdesign** [comment]
That's great, thanks a lot @atb00ker :clap: :clap:

**Comment by nemesisdesign** [comment]
**Update**: in the next weeks we should revise the README to ensure it's complete and all screenshots are up to date, especially the animated gif.
