### ISSUE TITLE
Document metrics stored in influxdb 

### ISSUE THREAD

**Issue by PabloCastellano** [openwisp/openwisp-monitoring#81]
We should collect in a documentation page all the metrics that we are storing in InfluxDB at the moment, including name, description, value type and keys.

**Comment by nemesisdesign** [comment]
This is related to https://github.com/openwisp/openwisp-monitoring/issues/44.

We should do it while implementing that, we should take advantage also to list the available charts, so we list the metrics we store and the chart we generate from these metrics.

**Comment by nepython** [comment]
`Description` is to be removed as per #28, so I would leave it :smile:
