### ISSUE TITLE
[charts] Add way to register and unregister new chart configurations

### ISSUE THREAD

**Issue by nemesisdesign** [openwisp/openwisp-monitoring#86]
Just like we're doing in https://github.com/openwisp/openwisp-notifications/pull/19/files#diff-e4c93b8a95c5a88dcf0c7b41e5c5ff5fR1

**Comment by nepython** [comment]
### Up for discussion
@nemesisdesign @PabloCastellano
After this feature, `OPENWISP_MONITORING_CHARTS` seems a bit redundant to me, hence I suggest that we remove it.
In case, I am missing anything, please correct me :)

**Comment by PabloCastellano** [comment]
@nepython I agree on removing ADDITIONAL_CHARTS but I think we can keep OPENWISP_MONITORING_CHARTS so that we don't need to call get_chart_configuration and check that the fields are correct every time.

**Comment by nepython** [comment]
>@nepython I agree on removing ADDITIONAL_CHARTS but I think we can keep OPENWISP_MONITORING_CHARTS so that we don't need to call get_chart_configuration and check that the fields are correct every time. WDYT?

I think, I didn't understand it fully. Please let me know if the current approach seems fine :smiley:
**+1** to not removing `OPENWISP_MONITORING_CHARTS`. I think it is still useful, use case: if the user wants to modify just one field in existing chart configuration, it seems more better approach.
