### ISSUE TITLE
[qa] Use Github pull templates

### ISSUE THREAD

**Issue by PabloCastellano** [openwisp/openwisp-monitoring#89]
Using pull templates like [explained here](https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates) we can improve our workflow and assure more quality in our PRs by default.

The template should contain at least the following checkboxes:

- [ ] I have updated the documentation (e.g. README.rst)
- [ ] I have written new test cases to avoid regressions

**Comment by nemesisdesign** [comment]
@PabloCastellano what if there's no need to update the docs? Should we have a case for that or just contemplate it with the same line like " I have updated the documentation in README.rst or no documentation update is needed"?

**Comment by PabloCastellano** [comment]
I don't see any problem in leaving the checkbox unmarked if there's no documentation to update. At least it makes it clearer that documentation is something to be updated unless necessary

**Comment by nemesisdesign** [comment]
Maybe we could add a line like "I have read and I am following the [OpenWISP contributing guidelines](http://openwisp.io/docs/developer/contributing.html#how-to-commit-your-changes-properly)"?

**Comment by PabloCastellano** [comment]
Maybe we can recommend reading it, but I would not make it a checkbox. I don't even remember myself all the guidelines :-D

**Comment by nemesisdesign** [comment]
Fair enough. As long as the link is there, some people will read it.
At some point we will also simplify and shorten the contribution guidelines.
